"""create initial tables

Revision ID: 016bcf0977f6
Revises: 
Create Date: 2025-10-18 12:46:35.089629

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '016bcf0977f6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('applications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('owner_team', sa.String(length=255), nullable=False),
    sa.Column('repo_url', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('releases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('version', sa.String(length=255), nullable=False),
    sa.Column('env', sa.Enum('DEV', 'PREPROD', 'PROD', name='environmentenum', native_enum=False), nullable=False),
    sa.Column('status', sa.Enum('CREATED', 'PENDING_PREPROD', 'PENDING_PROD', 'APPROVED_PREPROD', 'APPROVED_PROD', 'REJECTED', 'DEPLOYED', name='statusenum', native_enum=False), nullable=False),
    sa.Column('evidence_url', sa.String(length=1024), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('deployed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('approvals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('release_id', sa.Integer(), nullable=False),
    sa.Column('approver_email', sa.String(length=255), nullable=False),
    sa.Column('outcome', sa.Enum('APPROVED', 'REJECTED', name='outcomeenum', native_enum=False), nullable=False),
    sa.Column('notes', sa.String(length=1024), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['release_id'], ['releases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('approvals')
    op.drop_table('releases')
    op.drop_table('applications')
    # ### end Alembic commands ###
