"""implementing deployment_logs in releases

Revision ID: 4679a980ef5f
Revises: 016bcf0977f6
Create Date: 2025-10-18 18:07:52.677517

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4679a980ef5f'
down_revision: Union[str, Sequence[str], None] = '016bcf0977f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('releases', sa.Column('deployment_logs', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('releases', 'deployment_logs')
    # ### end Alembic commands ###
